<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EmailMarketingSystem" nsURI="http:///EmailMarketingSystem.ecore"
    nsPrefix="EmailMarketingSystem">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Campaign">
    <eOperations name="getAnalyticsDetails" ordered="false" lowerBound="1"/>
    <eOperations name="addSegment" ordered="false" lowerBound="1"/>
    <eOperations name="removeSegment" ordered="false" lowerBound="1"/>
    <eOperations name="viewSegmentDetails" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="campaignId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false"
        lowerBound="1" eType="#//CampaignStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analytics" ordered="false"
        eType="#//CampaignAnalytics"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" ordered="false"
        upperBound="-1" eType="#//Segment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CampaignStatus">
    <eLiterals name="Active"/>
    <eLiterals name="Inactive" value="1"/>
    <eLiterals name="Stopped" value="2"/>
    <eLiterals name="Expired" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CampaignAnalytics">
    <eOperations name="trackClick" ordered="false" lowerBound="1"/>
    <eOperations name="trackOpen" ordered="false" lowerBound="1"/>
    <eOperations name="trackConversion" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clicks" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opens" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversions" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eOperations name="addCondition" ordered="false" lowerBound="1"/>
    <eOperations name="removeCondition" ordered="false" lowerBound="1"/>
    <eOperations name="viewConditions" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segmentId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" ordered="false"
        upperBound="-1" eType="#//SegmentCondition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber">
    <eOperations name="addEmailCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="removeEmailCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="updatePreferences" ordered="false" lowerBound="1"/>
    <eOperations name="addSegment" ordered="false" lowerBound="1"/>
    <eOperations name="removeSegment" ordered="false" lowerBound="1"/>
    <eOperations name="viewSegmentDetails" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscriberId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscriptionDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" ordered="false"
        upperBound="-1" eType="#//Preference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" ordered="false"
        upperBound="-1" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emailCampaigns" ordered="false"
        upperBound="-1" eType="#//EmailCampaign" eOpposite="#//EmailCampaign/recipients"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preference">
    <eOperations name="updatePreference" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferenceId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmailCampaign" eSuperTypes="#//Campaign">
    <eOperations name="sendEmail" ordered="false" lowerBound="1"/>
    <eOperations name="trackCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="pauseCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="cancelCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="addEmailCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="removeEmailCampaign" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailCampaignId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" ordered="false"
        lowerBound="1" eType="#//EmailTemplate" eOpposite="#//EmailTemplate/emailCampaigns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emailResponses" ordered="false"
        upperBound="-1" eType="#//EmailResponse" eOpposite="#//EmailResponse/campaign"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipients" ordered="false"
        upperBound="-1" eType="#//Subscriber" eOpposite="#//Subscriber/emailCampaigns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmailTemplate">
    <eOperations name="addEmailCampaign" ordered="false" lowerBound="1"/>
    <eOperations name="removeEmailCampaign" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateId" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emailCampaigns" ordered="false"
        upperBound="-1" eType="#//EmailCampaign" eOpposite="#//EmailCampaign/template"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmailResponse">
    <eOperations name="getResponseTypeDetail" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseID" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseType" ordered="false"
        lowerBound="1" eType="#//ResponseType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" ordered="false"
        lowerBound="1" eType="#//Subscriber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campaign" ordered="false"
        lowerBound="1" eType="#//EmailCampaign" eOpposite="#//EmailCampaign/emailResponses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResponseType">
    <eLiterals name="OPENED"/>
    <eLiterals name="CLICKED" value="1"/>
    <eLiterals name="UNSUBSCRIBED" value="2"/>
    <eLiterals name="_BOUNCED" value="3">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value=" BOUNCED"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EmailCampaignStatus">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="CampaignStatus"/>
    </eAnnotations>
    <eLiterals name="Active"/>
    <eLiterals name="Expired" value="1"/>
    <eLiterals name="Stopped" value="2"/>
    <eLiterals name="Inactive" value="3"/>
  </eClassifiers>
</ecore:EPackage>
